server:
  http2:
    enabled: true
  port: 8080
spring:
  datasource:
    username: yuan
    password: yuan
    url: jdbc:mysql://localhost:3306/learning?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false
      &serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath*:sql/*.sql
    #    data: classpath*:sql/*.sql
    initialization-mode: always
logging:
  level:
    web: debug