server:
  http2:
    enabled: true
  port: 8080
spring:
  datasource:
    username: learning
    password: learning
    url: jdbc:mysql://localhost:3306/learning?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath*:sql/*.sql
    data: classpath*:sql/*.sql
    initialization-mode: always
logging:
  level:
    web: debug