server:
  http2:
    enabled: true
  port: 8080
spring:
  datasource:
    username: yuan
    password: yuan
    url: jdbc:mysql://localhost:3306/learning?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false
      &serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath*:sql/*.sql
    #    data: classpath*:sql/*.sql
  #    initialization-mode: always
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
logging:
  level:
    web: debug