spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learning?serverTimezone=Asia/Shanghai&useSSL=false
mybatis:
  mapper-locations: classpath*:/mappers/*.xml